# ~/.tmuxinator/bt.yml

project_name: bt
project_root: ~/Code/baton
socket_path: /tmp/tmux-pair-session
tabs:
  - editor: sleep 8 && vim
  - shell: git remote update origin; git pull --rebase origin
  - console/server:
      layout: even-vertical
      panes:
        - rails c
        - rails s
  - guard/faye:
      layout: even-vertical
      panes:
        - guard
        - rackup sync.ru -E production
  - starting: chmod 777 /tmp/tmux-pair-session; tmux set-window-option -t $SESSION:3 monitor-activity off; tmux set-window-option -t $SESSION:4 monitor-activity off; exit
