# ~/.tmuxinator/ccm.yml

project_name: ccm
project_root: ~/Code/cmr-claims-mobile
socket_path: /tmp/tmux-pair-session
windows:
  - editor:
      layout: 8087,238x60,0,0[238x44,0,0,0,238x15,0,45,5]
      panes:
        - vim
        -
  - shell: git remote update origin; git pull --rebase origin
  - build: wt titanium build -p ios
  - starting: chmod 777 /tmp/tmux-pair-session; tmux set-window-option -t $SESSION:3 monitor-activity off; tmux set-window-option -t $SESSION:4 monitor-activity off; sleep 2; kr; kz; exit; exit; exit
