# ~/.tmuxinator/qd.yml

project_name: qd
project_root: ~/Code/quadrantmetrics
tabs:
  - editor: sleep 8 && vim
  - shell: git remote update origin; git pull --rebase origin
  - console/server:
      layout: even-vertical
      panes:
        - sleep 3 && zeus c
        - sleep 3 && zeus s
  - zeus: zeus start
  - starting: tmux kill-window -t $SESSION:1; tmux link-window -s 0:1 -t $SESSION:1; sleep 2; tmux set-window-option -t $SESSION:5 monitor-activity off; exit
