# ~/.tmuxinator/rails.yml

project_name: rails
project_root: $WORKING_DIR
socket_path: /tmp/tmux-pair-session
windows:
  - editor:
      layout: 8087,238x60,0,0[238x44,0,0,0,238x15,0,45,5]
      panes:
        - vim
        -
  - shell: git remote update origin; git pull --rebase origin
  - console/server/jobs:
      layout: even-vertical
      panes:
        - wt rails s
        - wt rails c
        - wt rake jobs:work
  - starting: chmod 777 /tmp/tmux-pair-session; tmux set-window-option -t $SESSION:3 monitor-activity off; sleep 2; kr; exit
