# ~/.tmuxinator/sex.yml

project_name: sex
project_root: ~/Code/swagexpert
socket_path: /tmp/tmux-pair-session
windows:
  - editor: sleep 8 && vim
  - shell: git remote update origin; git pull --rebase origin
  - console/server:
      layout: even-vertical
      panes:
        - wt zeus c
        - wt zeus s
  - guard/faye/zeus:
      layout: even-vertical
      panes:
        - wt guard
        - wtzs
  - starting: chmod 777 /tmp/tmux-pair-session; tmux set-window-option -t $SESSION:3 monitor-activity off; tmux set-window-option -t $SESSION:4 monitor-activity off; exit
